// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb.Enum {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgdwYl9lbnVtKqICCglFcnJvckNvZGUSCwoHRGVmYXVs",
            "dBAAEgYKAk9LEAESDgoKRW50cnlFcnJvchACEhoKFkxvZ2luQWNjb3VudFVu",
            "RXhpeHRlbnQQAxIWChJMb2dpblBhc3N3b3JkRXJyb3IQBBIXChNSZWdpc3Rl",
            "ckFjY291bnRFeGl0EAUSDgoKQXV0aEZhaWxlZBAGEhMKD1RhYmxlVW5FeGlz",
            "dGVudBAHEhMKD1RhYmxlUGxheWVyRnVsbBAIEhIKDlRhYmxlSXNTdGFydGVk",
            "EAkSIQodVGFibGVHYW1lU3RhcnRQZXJtaXNzaW9uTGltaXQQChIXChNUYWJs",
            "ZVN0YXRlQ2FuTm90QmV0EAsSGQoVVGFibGVCZXRNb25leVVuRW5vdWdoEAwq",
            "JwoDU2V4EgoKBlVua25vdxAAEggKBE1hbGUQARIKCgZGZW1hbGUQAioWCghS",
            "b29tVHlwZRIKCgZUZXRyaXMQACo4CghQb2tlckh1YRIHCgNOaWwQABIHCgNU",
            "YW8QARIHCgNYaW4QAhIHCgNNZWkQAxIICgRGYW5nEAQqtgEKClBva2VyUG9p",
            "bnQSDAoIUG9pbnROaWwQABIKCgZQb2ludEEQARIKCgZQb2ludDIQAhIKCgZQ",
            "b2ludDMQAxIKCgZQb2ludDQQBBIKCgZQb2ludDUQBRIKCgZQb2ludDYQBhIK",
            "CgZQb2ludDcQBxIKCgZQb2ludDgQCBIKCgZQb2ludDkQCRIKCgZQb2ludFQQ",
            "ChIKCgZQb2ludEoQCxIKCgZQb2ludFEQDBIKCgZQb2ludEsQDUIdWhFzZXJ2",
            "ZXIvcGIvcGJfZW51baoCB1BiLkVudW1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.Enum.ErrorCode), typeof(global::Pb.Enum.Sex), typeof(global::Pb.Enum.RoomType), typeof(global::Pb.Enum.PokerHua), typeof(global::Pb.Enum.PokerPoint), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    /// <summary>
    ///默认值0
    /// </summary>
    [pbr::OriginalName("Default")] Default = 0,
    /// <summary>
    ///成功
    /// </summary>
    [pbr::OriginalName("OK")] Ok = 1,
    /// <summary>
    ///检验到客户端连接验证码失败（Entry模块握手失败）
    /// </summary>
    [pbr::OriginalName("EntryError")] EntryError = 2,
    /// <summary>
    ///登录账号不存在
    /// </summary>
    [pbr::OriginalName("LoginAccountUnExixtent")] LoginAccountUnExixtent = 3,
    /// <summary>
    ///登录密码错误
    /// </summary>
    [pbr::OriginalName("LoginPasswordError")] LoginPasswordError = 4,
    /// <summary>
    ///注册账号已存在
    /// </summary>
    [pbr::OriginalName("RegisterAccountExit")] RegisterAccountExit = 5,
    /// <summary>
    ///授权失败（先登录再进行长连接）
    /// </summary>
    [pbr::OriginalName("AuthFailed")] AuthFailed = 6,
    /// <summary>
    ///桌子不存在
    /// </summary>
    [pbr::OriginalName("TableUnExistent")] TableUnExistent = 7,
    /// <summary>
    ///桌子上玩家已满
    /// </summary>
    [pbr::OriginalName("TablePlayerFull")] TablePlayerFull = 8,
    /// <summary>
    ///桌子上的游戏已经开始了
    /// </summary>
    [pbr::OriginalName("TableIsStarted")] TableIsStarted = 9,
    /// <summary>
    ///桌子上开始游戏的权限不对
    /// </summary>
    [pbr::OriginalName("TableGameStartPermissionLimit")] TableGameStartPermissionLimit = 10,
    /// <summary>
    ///桌子当前状态下不能下注
    /// </summary>
    [pbr::OriginalName("TableStateCanNotBet")] TableStateCanNotBet = 11,
    /// <summary>
    ///下注的钱不足
    /// </summary>
    [pbr::OriginalName("TableBetMoneyUnEnough")] TableBetMoneyUnEnough = 12,
  }

  public enum Sex {
    /// <summary>
    ///春哥
    /// </summary>
    [pbr::OriginalName("Unknow")] Unknow = 0,
    /// <summary>
    ///男
    /// </summary>
    [pbr::OriginalName("Male")] Male = 1,
    /// <summary>
    ///女
    /// </summary>
    [pbr::OriginalName("Female")] Female = 2,
  }

  public enum RoomType {
    /// <summary>
    ///俄罗斯方块
    /// </summary>
    [pbr::OriginalName("Tetris")] Tetris = 0,
  }

  public enum PokerHua {
    [pbr::OriginalName("Nil")] Nil = 0,
    [pbr::OriginalName("Tao")] Tao = 1,
    [pbr::OriginalName("Xin")] Xin = 2,
    [pbr::OriginalName("Mei")] Mei = 3,
    [pbr::OriginalName("Fang")] Fang = 4,
  }

  public enum PokerPoint {
    [pbr::OriginalName("PointNil")] PointNil = 0,
    [pbr::OriginalName("PointA")] PointA = 1,
    [pbr::OriginalName("Point2")] Point2 = 2,
    [pbr::OriginalName("Point3")] Point3 = 3,
    [pbr::OriginalName("Point4")] Point4 = 4,
    [pbr::OriginalName("Point5")] Point5 = 5,
    [pbr::OriginalName("Point6")] Point6 = 6,
    [pbr::OriginalName("Point7")] Point7 = 7,
    [pbr::OriginalName("Point8")] Point8 = 8,
    [pbr::OriginalName("Point9")] Point9 = 9,
    [pbr::OriginalName("PointT")] PointT = 10,
    [pbr::OriginalName("PointJ")] PointJ = 11,
    [pbr::OriginalName("PointQ")] PointQ = 12,
    [pbr::OriginalName("PointK")] PointK = 13,
  }

  #endregion

}

#endregion Designer generated code
