// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: lobby.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb.Lobby {

  /// <summary>Holder for reflection information generated from lobby.proto</summary>
  public static partial class LobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for lobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgtsb2JieS5wcm90bxIIcGJfbG9iYnkaEGVycm9yX2NvZGUucHJvdG8ikwIK",
            "CFJlcUVudHJ5Eg4KBlNlY3JldBgBIAEoCRIMCgRVVUlEGAIgASgJEjEKCFBs",
            "YXRmb3JtGAMgASgOMh8ucGJfbG9iYnkuUmVxRW50cnkuRW51bVBsYXRmb3Jt",
            "EicKA0VudhgEIAEoDjIaLnBiX2xvYmJ5LlJlcUVudHJ5LkVudW1FbnYSEgoK",
            "UmVzVmVyc2lvbhgFIAEoCRITCgtHYW1lVmVyc2lvbhgGIAEoCSI5CgxFbnVt",
            "UGxhdGZvcm0SCAoETm9uZRAAEgsKB0FuZHJvaWQQARIHCgNJb3MQAhIJCgVX",
            "aW5QQxADIikKB0VudW1FbnYSBwoDRGV2EAASCQoFQWxwaGEQAhIKCgZPZmZp",
            "Y2UQASKjAQoJUmVzcEVudHJ5EiUKB0VyckNvZGUYASABKA4yFC5wYl9jb21t",
            "b24uRXJyb3JDb2RlEhAKCExvZ2luVXJsGAIgASgJEhMKC1JlZ2lzdGVyVXJs",
            "GAMgASgJEg4KBlRjcFVybBgEIAEoCRIUCgxXZWJTb2NrZXRVcmwYBSABKAkS",
            "EQoJQnVuZGxlVXJsGAYgASgJEg8KB09wZW5Mb2cYByABKAgiLQoIUmVxTG9n",
            "aW4SDwoHQWNjb3VudBgBIAEoCRIQCghQYXNzd29yZBgCIAEoCSIyCglSZXNw",
            "TG9naW4SJQoHRXJyQ29kZRgBIAEoDjIULnBiX2NvbW1vbi5FcnJvckNvZGUi",
            "DgoMUmVxTG9iYnlJbmZvIjYKDVJlc3BMb2JieUluZm8SJQoHRXJyQ29kZRgB",
            "IAEoDjIULnBiX2NvbW1vbi5FcnJvckNvZGVCH1oSc2VydmVyL3BiL3BiX2xv",
            "YmJ5qgIIUGIuTG9iYnliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pb.Common.ErrorCodeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Lobby.ReqEntry), global::Pb.Lobby.ReqEntry.Parser, new[]{ "Secret", "UUID", "Platform", "Env", "ResVersion", "GameVersion" }, null, new[]{ typeof(global::Pb.Lobby.ReqEntry.Types.EnumPlatform), typeof(global::Pb.Lobby.ReqEntry.Types.EnumEnv) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Lobby.RespEntry), global::Pb.Lobby.RespEntry.Parser, new[]{ "ErrCode", "LoginUrl", "RegisterUrl", "TcpUrl", "WebSocketUrl", "BundleUrl", "OpenLog" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Lobby.ReqLogin), global::Pb.Lobby.ReqLogin.Parser, new[]{ "Account", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Lobby.RespLogin), global::Pb.Lobby.RespLogin.Parser, new[]{ "ErrCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Lobby.ReqLobbyInfo), global::Pb.Lobby.ReqLobbyInfo.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Lobby.RespLobbyInfo), global::Pb.Lobby.RespLobbyInfo.Parser, new[]{ "ErrCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ReqEntry : pb::IMessage<ReqEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReqEntry> _parser = new pb::MessageParser<ReqEntry>(() => new ReqEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Lobby.LobbyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqEntry(ReqEntry other) : this() {
      secret_ = other.secret_;
      uUID_ = other.uUID_;
      platform_ = other.platform_;
      env_ = other.env_;
      resVersion_ = other.resVersion_;
      gameVersion_ = other.gameVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqEntry Clone() {
      return new ReqEntry(this);
    }

    /// <summary>Field number for the "Secret" field.</summary>
    public const int SecretFieldNumber = 1;
    private string secret_ = "";
    /// <summary>
    ///密钥
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Secret {
      get { return secret_; }
      set {
        secret_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 2;
    private string uUID_ = "";
    /// <summary>
    ///设备号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UUID {
      get { return uUID_; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Platform" field.</summary>
    public const int PlatformFieldNumber = 3;
    private global::Pb.Lobby.ReqEntry.Types.EnumPlatform platform_ = global::Pb.Lobby.ReqEntry.Types.EnumPlatform.None;
    /// <summary>
    ///平台
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pb.Lobby.ReqEntry.Types.EnumPlatform Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    /// <summary>Field number for the "Env" field.</summary>
    public const int EnvFieldNumber = 4;
    private global::Pb.Lobby.ReqEntry.Types.EnumEnv env_ = global::Pb.Lobby.ReqEntry.Types.EnumEnv.Dev;
    /// <summary>
    ///模式 0：正式 1：alpha 2：dev
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pb.Lobby.ReqEntry.Types.EnumEnv Env {
      get { return env_; }
      set {
        env_ = value;
      }
    }

    /// <summary>Field number for the "ResVersion" field.</summary>
    public const int ResVersionFieldNumber = 5;
    private string resVersion_ = "";
    /// <summary>
    ///客户端资源版本号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResVersion {
      get { return resVersion_; }
      set {
        resVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "GameVersion" field.</summary>
    public const int GameVersionFieldNumber = 6;
    private string gameVersion_ = "";
    /// <summary>
    ///游戏版本号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GameVersion {
      get { return gameVersion_; }
      set {
        gameVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Secret != other.Secret) return false;
      if (UUID != other.UUID) return false;
      if (Platform != other.Platform) return false;
      if (Env != other.Env) return false;
      if (ResVersion != other.ResVersion) return false;
      if (GameVersion != other.GameVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Secret.Length != 0) hash ^= Secret.GetHashCode();
      if (UUID.Length != 0) hash ^= UUID.GetHashCode();
      if (Platform != global::Pb.Lobby.ReqEntry.Types.EnumPlatform.None) hash ^= Platform.GetHashCode();
      if (Env != global::Pb.Lobby.ReqEntry.Types.EnumEnv.Dev) hash ^= Env.GetHashCode();
      if (ResVersion.Length != 0) hash ^= ResVersion.GetHashCode();
      if (GameVersion.Length != 0) hash ^= GameVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Secret.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Secret);
      }
      if (UUID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UUID);
      }
      if (Platform != global::Pb.Lobby.ReqEntry.Types.EnumPlatform.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Platform);
      }
      if (Env != global::Pb.Lobby.ReqEntry.Types.EnumEnv.Dev) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Env);
      }
      if (ResVersion.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ResVersion);
      }
      if (GameVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GameVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Secret.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Secret);
      }
      if (UUID.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UUID);
      }
      if (Platform != global::Pb.Lobby.ReqEntry.Types.EnumPlatform.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Platform);
      }
      if (Env != global::Pb.Lobby.ReqEntry.Types.EnumEnv.Dev) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Env);
      }
      if (ResVersion.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ResVersion);
      }
      if (GameVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GameVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Secret.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Secret);
      }
      if (UUID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
      }
      if (Platform != global::Pb.Lobby.ReqEntry.Types.EnumPlatform.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Platform);
      }
      if (Env != global::Pb.Lobby.ReqEntry.Types.EnumEnv.Dev) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Env);
      }
      if (ResVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResVersion);
      }
      if (GameVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqEntry other) {
      if (other == null) {
        return;
      }
      if (other.Secret.Length != 0) {
        Secret = other.Secret;
      }
      if (other.UUID.Length != 0) {
        UUID = other.UUID;
      }
      if (other.Platform != global::Pb.Lobby.ReqEntry.Types.EnumPlatform.None) {
        Platform = other.Platform;
      }
      if (other.Env != global::Pb.Lobby.ReqEntry.Types.EnumEnv.Dev) {
        Env = other.Env;
      }
      if (other.ResVersion.Length != 0) {
        ResVersion = other.ResVersion;
      }
      if (other.GameVersion.Length != 0) {
        GameVersion = other.GameVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Secret = input.ReadString();
            break;
          }
          case 18: {
            UUID = input.ReadString();
            break;
          }
          case 24: {
            Platform = (global::Pb.Lobby.ReqEntry.Types.EnumPlatform) input.ReadEnum();
            break;
          }
          case 32: {
            Env = (global::Pb.Lobby.ReqEntry.Types.EnumEnv) input.ReadEnum();
            break;
          }
          case 42: {
            ResVersion = input.ReadString();
            break;
          }
          case 50: {
            GameVersion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Secret = input.ReadString();
            break;
          }
          case 18: {
            UUID = input.ReadString();
            break;
          }
          case 24: {
            Platform = (global::Pb.Lobby.ReqEntry.Types.EnumPlatform) input.ReadEnum();
            break;
          }
          case 32: {
            Env = (global::Pb.Lobby.ReqEntry.Types.EnumEnv) input.ReadEnum();
            break;
          }
          case 42: {
            ResVersion = input.ReadString();
            break;
          }
          case 50: {
            GameVersion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ReqEntry message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum EnumPlatform {
        [pbr::OriginalName("None")] None = 0,
        [pbr::OriginalName("Android")] Android = 1,
        [pbr::OriginalName("Ios")] Ios = 2,
        [pbr::OriginalName("WinPC")] WinPc = 3,
      }

      public enum EnumEnv {
        /// <summary>
        ///开发服
        /// </summary>
        [pbr::OriginalName("Dev")] Dev = 0,
        /// <summary>
        ///内网测试服
        /// </summary>
        [pbr::OriginalName("Alpha")] Alpha = 2,
        /// <summary>
        ///正式服
        /// </summary>
        [pbr::OriginalName("Office")] Office = 1,
      }

    }
    #endregion

  }

  /// <summary>
  ///入口消息resp，服务端将登录、注册、长连接等地址下发
  /// </summary>
  public sealed partial class RespEntry : pb::IMessage<RespEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespEntry> _parser = new pb::MessageParser<RespEntry>(() => new RespEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RespEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Lobby.LobbyReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespEntry(RespEntry other) : this() {
      errCode_ = other.errCode_;
      loginUrl_ = other.loginUrl_;
      registerUrl_ = other.registerUrl_;
      tcpUrl_ = other.tcpUrl_;
      webSocketUrl_ = other.webSocketUrl_;
      bundleUrl_ = other.bundleUrl_;
      openLog_ = other.openLog_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespEntry Clone() {
      return new RespEntry(this);
    }

    /// <summary>Field number for the "ErrCode" field.</summary>
    public const int ErrCodeFieldNumber = 1;
    private global::Pb.Common.ErrorCode errCode_ = global::Pb.Common.ErrorCode.Default;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pb.Common.ErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    /// <summary>Field number for the "LoginUrl" field.</summary>
    public const int LoginUrlFieldNumber = 2;
    private string loginUrl_ = "";
    /// <summary>
    ///登录http地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginUrl {
      get { return loginUrl_; }
      set {
        loginUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RegisterUrl" field.</summary>
    public const int RegisterUrlFieldNumber = 3;
    private string registerUrl_ = "";
    /// <summary>
    ///注册http地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RegisterUrl {
      get { return registerUrl_; }
      set {
        registerUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TcpUrl" field.</summary>
    public const int TcpUrlFieldNumber = 4;
    private string tcpUrl_ = "";
    /// <summary>
    /// TCP连接地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TcpUrl {
      get { return tcpUrl_; }
      set {
        tcpUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "WebSocketUrl" field.</summary>
    public const int WebSocketUrlFieldNumber = 5;
    private string webSocketUrl_ = "";
    /// <summary>
    /// Websocket连接地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string WebSocketUrl {
      get { return webSocketUrl_; }
      set {
        webSocketUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BundleUrl" field.</summary>
    public const int BundleUrlFieldNumber = 6;
    private string bundleUrl_ = "";
    /// <summary>
    ///下补丁的链接
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BundleUrl {
      get { return bundleUrl_; }
      set {
        bundleUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "OpenLog" field.</summary>
    public const int OpenLogFieldNumber = 7;
    private bool openLog_;
    /// <summary>
    ///客户端是否开日志
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool OpenLog {
      get { return openLog_; }
      set {
        openLog_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RespEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RespEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrCode != other.ErrCode) return false;
      if (LoginUrl != other.LoginUrl) return false;
      if (RegisterUrl != other.RegisterUrl) return false;
      if (TcpUrl != other.TcpUrl) return false;
      if (WebSocketUrl != other.WebSocketUrl) return false;
      if (BundleUrl != other.BundleUrl) return false;
      if (OpenLog != other.OpenLog) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrCode != global::Pb.Common.ErrorCode.Default) hash ^= ErrCode.GetHashCode();
      if (LoginUrl.Length != 0) hash ^= LoginUrl.GetHashCode();
      if (RegisterUrl.Length != 0) hash ^= RegisterUrl.GetHashCode();
      if (TcpUrl.Length != 0) hash ^= TcpUrl.GetHashCode();
      if (WebSocketUrl.Length != 0) hash ^= WebSocketUrl.GetHashCode();
      if (BundleUrl.Length != 0) hash ^= BundleUrl.GetHashCode();
      if (OpenLog != false) hash ^= OpenLog.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrCode);
      }
      if (LoginUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LoginUrl);
      }
      if (RegisterUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RegisterUrl);
      }
      if (TcpUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TcpUrl);
      }
      if (WebSocketUrl.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(WebSocketUrl);
      }
      if (BundleUrl.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(BundleUrl);
      }
      if (OpenLog != false) {
        output.WriteRawTag(56);
        output.WriteBool(OpenLog);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrCode);
      }
      if (LoginUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LoginUrl);
      }
      if (RegisterUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RegisterUrl);
      }
      if (TcpUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TcpUrl);
      }
      if (WebSocketUrl.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(WebSocketUrl);
      }
      if (BundleUrl.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(BundleUrl);
      }
      if (OpenLog != false) {
        output.WriteRawTag(56);
        output.WriteBool(OpenLog);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (LoginUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginUrl);
      }
      if (RegisterUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RegisterUrl);
      }
      if (TcpUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TcpUrl);
      }
      if (WebSocketUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WebSocketUrl);
      }
      if (BundleUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BundleUrl);
      }
      if (OpenLog != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RespEntry other) {
      if (other == null) {
        return;
      }
      if (other.ErrCode != global::Pb.Common.ErrorCode.Default) {
        ErrCode = other.ErrCode;
      }
      if (other.LoginUrl.Length != 0) {
        LoginUrl = other.LoginUrl;
      }
      if (other.RegisterUrl.Length != 0) {
        RegisterUrl = other.RegisterUrl;
      }
      if (other.TcpUrl.Length != 0) {
        TcpUrl = other.TcpUrl;
      }
      if (other.WebSocketUrl.Length != 0) {
        WebSocketUrl = other.WebSocketUrl;
      }
      if (other.BundleUrl.Length != 0) {
        BundleUrl = other.BundleUrl;
      }
      if (other.OpenLog != false) {
        OpenLog = other.OpenLog;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrCode = (global::Pb.Common.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            LoginUrl = input.ReadString();
            break;
          }
          case 26: {
            RegisterUrl = input.ReadString();
            break;
          }
          case 34: {
            TcpUrl = input.ReadString();
            break;
          }
          case 42: {
            WebSocketUrl = input.ReadString();
            break;
          }
          case 50: {
            BundleUrl = input.ReadString();
            break;
          }
          case 56: {
            OpenLog = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrCode = (global::Pb.Common.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            LoginUrl = input.ReadString();
            break;
          }
          case 26: {
            RegisterUrl = input.ReadString();
            break;
          }
          case 34: {
            TcpUrl = input.ReadString();
            break;
          }
          case 42: {
            WebSocketUrl = input.ReadString();
            break;
          }
          case 50: {
            BundleUrl = input.ReadString();
            break;
          }
          case 56: {
            OpenLog = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ReqLogin : pb::IMessage<ReqLogin>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReqLogin> _parser = new pb::MessageParser<ReqLogin>(() => new ReqLogin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqLogin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Lobby.LobbyReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqLogin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqLogin(ReqLogin other) : this() {
      account_ = other.account_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqLogin Clone() {
      return new ReqLogin(this);
    }

    /// <summary>Field number for the "Account" field.</summary>
    public const int AccountFieldNumber = 1;
    private string account_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqLogin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqLogin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Account != other.Account) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Account.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Account.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqLogin other) {
      if (other == null) {
        return;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RespLogin : pb::IMessage<RespLogin>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespLogin> _parser = new pb::MessageParser<RespLogin>(() => new RespLogin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RespLogin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Lobby.LobbyReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespLogin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespLogin(RespLogin other) : this() {
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespLogin Clone() {
      return new RespLogin(this);
    }

    /// <summary>Field number for the "ErrCode" field.</summary>
    public const int ErrCodeFieldNumber = 1;
    private global::Pb.Common.ErrorCode errCode_ = global::Pb.Common.ErrorCode.Default;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pb.Common.ErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RespLogin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RespLogin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrCode != global::Pb.Common.ErrorCode.Default) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RespLogin other) {
      if (other == null) {
        return;
      }
      if (other.ErrCode != global::Pb.Common.ErrorCode.Default) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrCode = (global::Pb.Common.ErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrCode = (global::Pb.Common.ErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ReqLobbyInfo : pb::IMessage<ReqLobbyInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReqLobbyInfo> _parser = new pb::MessageParser<ReqLobbyInfo>(() => new ReqLobbyInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqLobbyInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Lobby.LobbyReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqLobbyInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqLobbyInfo(ReqLobbyInfo other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqLobbyInfo Clone() {
      return new ReqLobbyInfo(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqLobbyInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqLobbyInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqLobbyInfo other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class RespLobbyInfo : pb::IMessage<RespLobbyInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespLobbyInfo> _parser = new pb::MessageParser<RespLobbyInfo>(() => new RespLobbyInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RespLobbyInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.Lobby.LobbyReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespLobbyInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespLobbyInfo(RespLobbyInfo other) : this() {
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RespLobbyInfo Clone() {
      return new RespLobbyInfo(this);
    }

    /// <summary>Field number for the "ErrCode" field.</summary>
    public const int ErrCodeFieldNumber = 1;
    private global::Pb.Common.ErrorCode errCode_ = global::Pb.Common.ErrorCode.Default;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pb.Common.ErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RespLobbyInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RespLobbyInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrCode != global::Pb.Common.ErrorCode.Default) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ErrCode != global::Pb.Common.ErrorCode.Default) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RespLobbyInfo other) {
      if (other == null) {
        return;
      }
      if (other.ErrCode != global::Pb.Common.ErrorCode.Default) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrCode = (global::Pb.Common.ErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrCode = (global::Pb.Common.ErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
