// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: http.proto

package pb_http

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_enum "server/pb/pb_enum"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqHandShake_EnumPlatform int32

const (
	ReqHandShake_None    ReqHandShake_EnumPlatform = 0
	ReqHandShake_Android ReqHandShake_EnumPlatform = 1
	ReqHandShake_Ios     ReqHandShake_EnumPlatform = 2
	ReqHandShake_WinPC   ReqHandShake_EnumPlatform = 3
)

// Enum value maps for ReqHandShake_EnumPlatform.
var (
	ReqHandShake_EnumPlatform_name = map[int32]string{
		0: "None",
		1: "Android",
		2: "Ios",
		3: "WinPC",
	}
	ReqHandShake_EnumPlatform_value = map[string]int32{
		"None":    0,
		"Android": 1,
		"Ios":     2,
		"WinPC":   3,
	}
)

func (x ReqHandShake_EnumPlatform) Enum() *ReqHandShake_EnumPlatform {
	p := new(ReqHandShake_EnumPlatform)
	*p = x
	return p
}

func (x ReqHandShake_EnumPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqHandShake_EnumPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_http_proto_enumTypes[0].Descriptor()
}

func (ReqHandShake_EnumPlatform) Type() protoreflect.EnumType {
	return &file_http_proto_enumTypes[0]
}

func (x ReqHandShake_EnumPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqHandShake_EnumPlatform.Descriptor instead.
func (ReqHandShake_EnumPlatform) EnumDescriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{0, 0}
}

type ReqHandShake_EnumEnv int32

const (
	ReqHandShake_Development ReqHandShake_EnumEnv = 0 //开发服
	ReqHandShake_Production  ReqHandShake_EnumEnv = 1 //正式服
)

// Enum value maps for ReqHandShake_EnumEnv.
var (
	ReqHandShake_EnumEnv_name = map[int32]string{
		0: "Development",
		1: "Production",
	}
	ReqHandShake_EnumEnv_value = map[string]int32{
		"Development": 0,
		"Production":  1,
	}
)

func (x ReqHandShake_EnumEnv) Enum() *ReqHandShake_EnumEnv {
	p := new(ReqHandShake_EnumEnv)
	*p = x
	return p
}

func (x ReqHandShake_EnumEnv) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqHandShake_EnumEnv) Descriptor() protoreflect.EnumDescriptor {
	return file_http_proto_enumTypes[1].Descriptor()
}

func (ReqHandShake_EnumEnv) Type() protoreflect.EnumType {
	return &file_http_proto_enumTypes[1]
}

func (x ReqHandShake_EnumEnv) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqHandShake_EnumEnv.Descriptor instead.
func (ReqHandShake_EnumEnv) EnumDescriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{0, 1}
}

type ReqHandShake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret      string                    `protobuf:"bytes,1,opt,name=Secret,proto3" json:"Secret,omitempty"`                                             //密钥
	UUID        string                    `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`                                                 //设备号
	Platform    ReqHandShake_EnumPlatform `protobuf:"varint,3,opt,name=Platform,proto3,enum=pb_http.ReqHandShake_EnumPlatform" json:"Platform,omitempty"` //平台
	Env         ReqHandShake_EnumEnv      `protobuf:"varint,4,opt,name=Env,proto3,enum=pb_http.ReqHandShake_EnumEnv" json:"Env,omitempty"`                //模式 0：正式 1：alpha 2：dev
	ResVersion  string                    `protobuf:"bytes,5,opt,name=ResVersion,proto3" json:"ResVersion,omitempty"`                                     //客户端资源版本号
	GameVersion string                    `protobuf:"bytes,6,opt,name=GameVersion,proto3" json:"GameVersion,omitempty"`                                   //游戏版本号
}

func (x *ReqHandShake) Reset() {
	*x = ReqHandShake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqHandShake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHandShake) ProtoMessage() {}

func (x *ReqHandShake) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHandShake.ProtoReflect.Descriptor instead.
func (*ReqHandShake) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{0}
}

func (x *ReqHandShake) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *ReqHandShake) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ReqHandShake) GetPlatform() ReqHandShake_EnumPlatform {
	if x != nil {
		return x.Platform
	}
	return ReqHandShake_None
}

func (x *ReqHandShake) GetEnv() ReqHandShake_EnumEnv {
	if x != nil {
		return x.Env
	}
	return ReqHandShake_Development
}

func (x *ReqHandShake) GetResVersion() string {
	if x != nil {
		return x.ResVersion
	}
	return ""
}

func (x *ReqHandShake) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

//入口消息resp，服务端将登录、注册、长连接等地址下发
type RespHandShake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode      pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"`
	LoginUrl     string            `protobuf:"bytes,2,opt,name=LoginUrl,proto3" json:"LoginUrl,omitempty"`         //登录http地址
	RegisterUrl  string            `protobuf:"bytes,3,opt,name=RegisterUrl,proto3" json:"RegisterUrl,omitempty"`   //注册http地址
	TcpUrl       string            `protobuf:"bytes,4,opt,name=TcpUrl,proto3" json:"TcpUrl,omitempty"`             // TCP连接地址
	WebSocketUrl string            `protobuf:"bytes,5,opt,name=WebSocketUrl,proto3" json:"WebSocketUrl,omitempty"` // Websocket连接地址
}

func (x *RespHandShake) Reset() {
	*x = RespHandShake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespHandShake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespHandShake) ProtoMessage() {}

func (x *RespHandShake) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespHandShake.ProtoReflect.Descriptor instead.
func (*RespHandShake) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{1}
}

func (x *RespHandShake) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

func (x *RespHandShake) GetLoginUrl() string {
	if x != nil {
		return x.LoginUrl
	}
	return ""
}

func (x *RespHandShake) GetRegisterUrl() string {
	if x != nil {
		return x.RegisterUrl
	}
	return ""
}

func (x *RespHandShake) GetTcpUrl() string {
	if x != nil {
		return x.TcpUrl
	}
	return ""
}

func (x *RespHandShake) GetWebSocketUrl() string {
	if x != nil {
		return x.WebSocketUrl
	}
	return ""
}

type ReqRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *ReqRegister) Reset() {
	*x = ReqRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegister) ProtoMessage() {}

func (x *ReqRegister) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegister.ProtoReflect.Descriptor instead.
func (*ReqRegister) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{2}
}

func (x *ReqRegister) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqRegister) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"`
}

func (x *RespRegister) Reset() {
	*x = RespRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespRegister) ProtoMessage() {}

func (x *RespRegister) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespRegister.ProtoReflect.Descriptor instead.
func (*RespRegister) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{3}
}

func (x *RespRegister) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

type ReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{4}
}

func (x *ReqLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"`
	Token   string            `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *RespLogin) Reset() {
	*x = RespLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogin) ProtoMessage() {}

func (x *RespLogin) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogin.ProtoReflect.Descriptor instead.
func (*RespLogin) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{5}
}

func (x *RespLogin) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

func (x *RespLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_http_proto protoreflect.FileDescriptor

var file_http_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x62,
	0x5f, 0x68, 0x74, 0x74, 0x70, 0x1a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd4, 0x02, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68, 0x61,
	0x6b, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x3e,
	0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x70, 0x62, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x61,
	0x6e, 0x64, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x2f,
	0x0a, 0x03, 0x45, 0x6e, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x62,
	0x5f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68, 0x61,
	0x6b, 0x65, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x45, 0x6e, 0x76, 0x52, 0x03, 0x45, 0x6e, 0x76, 0x12,
	0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x20, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x39, 0x0a, 0x0c, 0x45, 0x6e, 0x75, 0x6d, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41,
	0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x6f, 0x73, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x69, 0x6e, 0x50, 0x43, 0x10, 0x03, 0x22, 0x2a, 0x0a, 0x07,
	0x45, 0x6e, 0x75, 0x6d, 0x45, 0x6e, 0x76, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x22, 0xb7, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x70, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62,
	0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x63, 0x70, 0x55, 0x72, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x63, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x22,
	0x0a, 0x0c, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x55,
	0x72, 0x6c, 0x22, 0x43, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3c, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x4f, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x1d, 0x5a, 0x11, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x68, 0x74, 0x74, 0x70, 0xaa, 0x02, 0x07,
	0x50, 0x62, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_proto_rawDescOnce sync.Once
	file_http_proto_rawDescData = file_http_proto_rawDesc
)

func file_http_proto_rawDescGZIP() []byte {
	file_http_proto_rawDescOnce.Do(func() {
		file_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_proto_rawDescData)
	})
	return file_http_proto_rawDescData
}

var file_http_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_http_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_http_proto_goTypes = []interface{}{
	(ReqHandShake_EnumPlatform)(0), // 0: pb_http.ReqHandShake.EnumPlatform
	(ReqHandShake_EnumEnv)(0),      // 1: pb_http.ReqHandShake.EnumEnv
	(*ReqHandShake)(nil),           // 2: pb_http.ReqHandShake
	(*RespHandShake)(nil),          // 3: pb_http.RespHandShake
	(*ReqRegister)(nil),            // 4: pb_http.ReqRegister
	(*RespRegister)(nil),           // 5: pb_http.RespRegister
	(*ReqLogin)(nil),               // 6: pb_http.ReqLogin
	(*RespLogin)(nil),              // 7: pb_http.RespLogin
	(pb_enum.ErrorCode)(0),         // 8: pb_enum.ErrorCode
}
var file_http_proto_depIdxs = []int32{
	0, // 0: pb_http.ReqHandShake.Platform:type_name -> pb_http.ReqHandShake.EnumPlatform
	1, // 1: pb_http.ReqHandShake.Env:type_name -> pb_http.ReqHandShake.EnumEnv
	8, // 2: pb_http.RespHandShake.ErrCode:type_name -> pb_enum.ErrorCode
	8, // 3: pb_http.RespRegister.ErrCode:type_name -> pb_enum.ErrorCode
	8, // 4: pb_http.RespLogin.ErrCode:type_name -> pb_enum.ErrorCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_http_proto_init() }
func file_http_proto_init() {
	if File_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqHandShake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespHandShake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_proto_goTypes,
		DependencyIndexes: file_http_proto_depIdxs,
		EnumInfos:         file_http_proto_enumTypes,
		MessageInfos:      file_http_proto_msgTypes,
	}.Build()
	File_http_proto = out.File
	file_http_proto_rawDesc = nil
	file_http_proto_goTypes = nil
	file_http_proto_depIdxs = nil
}
