// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: bjl.proto

package pb_bjl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_common "server/pb/pb_common"
	pb_enum "server/pb/pb_enum"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//下注区域
type EnumBetArea int32

const (
	EnumBetArea_AreaNone      EnumBetArea = 0
	EnumBetArea_AreaXian      EnumBetArea = 1
	EnumBetArea_AreaZhuang    EnumBetArea = 2
	EnumBetArea_AreaHe        EnumBetArea = 3
	EnumBetArea_AreaXianDui   EnumBetArea = 4
	EnumBetArea_AreaZhuangDui EnumBetArea = 5
)

// Enum value maps for EnumBetArea.
var (
	EnumBetArea_name = map[int32]string{
		0: "AreaNone",
		1: "AreaXian",
		2: "AreaZhuang",
		3: "AreaHe",
		4: "AreaXianDui",
		5: "AreaZhuangDui",
	}
	EnumBetArea_value = map[string]int32{
		"AreaNone":      0,
		"AreaXian":      1,
		"AreaZhuang":    2,
		"AreaHe":        3,
		"AreaXianDui":   4,
		"AreaZhuangDui": 5,
	}
)

func (x EnumBetArea) Enum() *EnumBetArea {
	p := new(EnumBetArea)
	*p = x
	return p
}

func (x EnumBetArea) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumBetArea) Descriptor() protoreflect.EnumDescriptor {
	return file_bjl_proto_enumTypes[0].Descriptor()
}

func (EnumBetArea) Type() protoreflect.EnumType {
	return &file_bjl_proto_enumTypes[0]
}

func (x EnumBetArea) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumBetArea.Descriptor instead.
func (EnumBetArea) EnumDescriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{0}
}

type EnumGameStatus int32

const (
	EnumGameStatus_None   EnumGameStatus = 0
	EnumGameStatus_Ready  EnumGameStatus = 1
	EnumGameStatus_Bet    EnumGameStatus = 2
	EnumGameStatus_Send   EnumGameStatus = 3
	EnumGameStatus_Show   EnumGameStatus = 4
	EnumGameStatus_Settle EnumGameStatus = 5
)

// Enum value maps for EnumGameStatus.
var (
	EnumGameStatus_name = map[int32]string{
		0: "None",
		1: "Ready",
		2: "Bet",
		3: "Send",
		4: "Show",
		5: "Settle",
	}
	EnumGameStatus_value = map[string]int32{
		"None":   0,
		"Ready":  1,
		"Bet":    2,
		"Send":   3,
		"Show":   4,
		"Settle": 5,
	}
)

func (x EnumGameStatus) Enum() *EnumGameStatus {
	p := new(EnumGameStatus)
	*p = x
	return p
}

func (x EnumGameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumGameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bjl_proto_enumTypes[1].Descriptor()
}

func (EnumGameStatus) Type() protoreflect.EnumType {
	return &file_bjl_proto_enumTypes[1]
}

func (x EnumGameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumGameStatus.Descriptor instead.
func (EnumGameStatus) EnumDescriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{1}
}

type EnumWinType int32

const (
	EnumWinType_Xian   EnumWinType = 0 //闲赢
	EnumWinType_Zhuang EnumWinType = 1 //庄赢
	EnumWinType_He     EnumWinType = 2 //和
)

// Enum value maps for EnumWinType.
var (
	EnumWinType_name = map[int32]string{
		0: "Xian",
		1: "Zhuang",
		2: "He",
	}
	EnumWinType_value = map[string]int32{
		"Xian":   0,
		"Zhuang": 1,
		"He":     2,
	}
)

func (x EnumWinType) Enum() *EnumWinType {
	p := new(EnumWinType)
	*p = x
	return p
}

func (x EnumWinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumWinType) Descriptor() protoreflect.EnumDescriptor {
	return file_bjl_proto_enumTypes[2].Descriptor()
}

func (EnumWinType) Type() protoreflect.EnumType {
	return &file_bjl_proto_enumTypes[2]
}

func (x EnumWinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumWinType.Descriptor instead.
func (EnumWinType) EnumDescriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{2}
}

type PushRoomInfoChange_EnumChangeType int32

const (
	PushRoomInfoChange_OnCreate  PushRoomInfoChange_EnumChangeType = 0 //创建
	PushRoomInfoChange_OnDestroy PushRoomInfoChange_EnumChangeType = 1 //销毁
)

// Enum value maps for PushRoomInfoChange_EnumChangeType.
var (
	PushRoomInfoChange_EnumChangeType_name = map[int32]string{
		0: "OnCreate",
		1: "OnDestroy",
	}
	PushRoomInfoChange_EnumChangeType_value = map[string]int32{
		"OnCreate":  0,
		"OnDestroy": 1,
	}
)

func (x PushRoomInfoChange_EnumChangeType) Enum() *PushRoomInfoChange_EnumChangeType {
	p := new(PushRoomInfoChange_EnumChangeType)
	*p = x
	return p
}

func (x PushRoomInfoChange_EnumChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushRoomInfoChange_EnumChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_bjl_proto_enumTypes[3].Descriptor()
}

func (PushRoomInfoChange_EnumChangeType) Type() protoreflect.EnumType {
	return &file_bjl_proto_enumTypes[3]
}

func (x PushRoomInfoChange_EnumChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushRoomInfoChange_EnumChangeType.Descriptor instead.
func (PushRoomInfoChange_EnumChangeType) EnumDescriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{5, 0}
}

type BroadcastTablePlayerChange_EnumChangeType int32

const (
	BroadcastTablePlayerChange_Join  BroadcastTablePlayerChange_EnumChangeType = 0 //加入桌子
	BroadcastTablePlayerChange_Leave BroadcastTablePlayerChange_EnumChangeType = 1 //离开桌子坐位
)

// Enum value maps for BroadcastTablePlayerChange_EnumChangeType.
var (
	BroadcastTablePlayerChange_EnumChangeType_name = map[int32]string{
		0: "Join",
		1: "Leave",
	}
	BroadcastTablePlayerChange_EnumChangeType_value = map[string]int32{
		"Join":  0,
		"Leave": 1,
	}
)

func (x BroadcastTablePlayerChange_EnumChangeType) Enum() *BroadcastTablePlayerChange_EnumChangeType {
	p := new(BroadcastTablePlayerChange_EnumChangeType)
	*p = x
	return p
}

func (x BroadcastTablePlayerChange_EnumChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BroadcastTablePlayerChange_EnumChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_bjl_proto_enumTypes[4].Descriptor()
}

func (BroadcastTablePlayerChange_EnumChangeType) Type() protoreflect.EnumType {
	return &file_bjl_proto_enumTypes[4]
}

func (x BroadcastTablePlayerChange_EnumChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BroadcastTablePlayerChange_EnumChangeType.Descriptor instead.
func (BroadcastTablePlayerChange_EnumChangeType) EnumDescriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{8, 0}
}

type ReqCreateBjl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"` //游戏桌子名称
}

func (x *ReqCreateBjl) Reset() {
	*x = ReqCreateBjl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCreateBjl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateBjl) ProtoMessage() {}

func (x *ReqCreateBjl) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateBjl.ProtoReflect.Descriptor instead.
func (*ReqCreateBjl) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{0}
}

func (x *ReqCreateBjl) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type RespCreteBjl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"`
	ID      string            `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"` //服务器创建成功后返回的桌子的ID
}

func (x *RespCreteBjl) Reset() {
	*x = RespCreteBjl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespCreteBjl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespCreteBjl) ProtoMessage() {}

func (x *RespCreteBjl) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespCreteBjl.ProtoReflect.Descriptor instead.
func (*RespCreteBjl) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{1}
}

func (x *RespCreteBjl) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

func (x *RespCreteBjl) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

//是否订阅房间消息
type ReqSubscribeRoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSubscribe bool `protobuf:"varint,1,opt,name=IsSubscribe,proto3" json:"IsSubscribe,omitempty"` // true,开始订阅，false,取消订阅
}

func (x *ReqSubscribeRoomInfo) Reset() {
	*x = ReqSubscribeRoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSubscribeRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSubscribeRoomInfo) ProtoMessage() {}

func (x *ReqSubscribeRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSubscribeRoomInfo.ProtoReflect.Descriptor instead.
func (*ReqSubscribeRoomInfo) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSubscribeRoomInfo) GetIsSubscribe() bool {
	if x != nil {
		return x.IsSubscribe
	}
	return false
}

//服务器向客户端同步房间信息
type TableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId         string `protobuf:"bytes,1,opt,name=TableId,proto3" json:"TableId,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatorUId      string `protobuf:"bytes,3,opt,name=CreatorUId,proto3" json:"CreatorUId,omitempty"`
	CreatorNickName string `protobuf:"bytes,4,opt,name=CreatorNickName,proto3" json:"CreatorNickName,omitempty"`
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{3}
}

func (x *TableInfo) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *TableInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableInfo) GetCreatorUId() string {
	if x != nil {
		return x.CreatorUId
	}
	return ""
}

func (x *TableInfo) GetCreatorNickName() string {
	if x != nil {
		return x.CreatorNickName
	}
	return ""
}

type RespSubscribeRoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode      pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"`
	AllTableInfo []*TableInfo      `protobuf:"bytes,2,rep,name=AllTableInfo,proto3" json:"AllTableInfo,omitempty"`
}

func (x *RespSubscribeRoomInfo) Reset() {
	*x = RespSubscribeRoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespSubscribeRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSubscribeRoomInfo) ProtoMessage() {}

func (x *RespSubscribeRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSubscribeRoomInfo.ProtoReflect.Descriptor instead.
func (*RespSubscribeRoomInfo) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{4}
}

func (x *RespSubscribeRoomInfo) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

func (x *RespSubscribeRoomInfo) GetAllTableInfo() []*TableInfo {
	if x != nil {
		return x.AllTableInfo
	}
	return nil
}

type PushRoomInfoChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangeType        PushRoomInfoChange_EnumChangeType `protobuf:"varint,1,opt,name=ChangeType,proto3,enum=pb_bjl.PushRoomInfoChange_EnumChangeType" json:"ChangeType,omitempty"`
	OnChangeTableInfo *TableInfo                        `protobuf:"bytes,2,opt,name=onChangeTableInfo,proto3" json:"onChangeTableInfo,omitempty"` //变化量
	AllTableInfo      []*TableInfo                      `protobuf:"bytes,3,rep,name=AllTableInfo,proto3" json:"AllTableInfo,omitempty"`           //总量
}

func (x *PushRoomInfoChange) Reset() {
	*x = PushRoomInfoChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushRoomInfoChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomInfoChange) ProtoMessage() {}

func (x *PushRoomInfoChange) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomInfoChange.ProtoReflect.Descriptor instead.
func (*PushRoomInfoChange) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{5}
}

func (x *PushRoomInfoChange) GetChangeType() PushRoomInfoChange_EnumChangeType {
	if x != nil {
		return x.ChangeType
	}
	return PushRoomInfoChange_OnCreate
}

func (x *PushRoomInfoChange) GetOnChangeTableInfo() *TableInfo {
	if x != nil {
		return x.OnChangeTableInfo
	}
	return nil
}

func (x *PushRoomInfoChange) GetAllTableInfo() []*TableInfo {
	if x != nil {
		return x.AllTableInfo
	}
	return nil
}

type ReqJoinTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId string `protobuf:"bytes,1,opt,name=TableId,proto3" json:"TableId,omitempty"` //要加入的桌子Id
}

func (x *ReqJoinTable) Reset() {
	*x = ReqJoinTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJoinTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJoinTable) ProtoMessage() {}

func (x *ReqJoinTable) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJoinTable.ProtoReflect.Descriptor instead.
func (*ReqJoinTable) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{6}
}

func (x *ReqJoinTable) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type RespJoinTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"` // ok或err
}

func (x *RespJoinTable) Reset() {
	*x = RespJoinTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinTable) ProtoMessage() {}

func (x *RespJoinTable) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinTable.ProtoReflect.Descriptor instead.
func (*RespJoinTable) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{7}
}

func (x *RespJoinTable) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

type BroadcastTablePlayerChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangeType     BroadcastTablePlayerChange_EnumChangeType `protobuf:"varint,1,opt,name=ChangeType,proto3,enum=pb_bjl.BroadcastTablePlayerChange_EnumChangeType" json:"ChangeType,omitempty"`
	OnChangePlayer *BjlPlayer                                `protobuf:"bytes,2,opt,name=OnChangePlayer,proto3" json:"OnChangePlayer,omitempty"` //变量
	AllPlayer      []*BjlPlayer                              `protobuf:"bytes,3,rep,name=AllPlayer,proto3" json:"AllPlayer,omitempty"`           //总量
}

func (x *BroadcastTablePlayerChange) Reset() {
	*x = BroadcastTablePlayerChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastTablePlayerChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastTablePlayerChange) ProtoMessage() {}

func (x *BroadcastTablePlayerChange) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastTablePlayerChange.ProtoReflect.Descriptor instead.
func (*BroadcastTablePlayerChange) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{8}
}

func (x *BroadcastTablePlayerChange) GetChangeType() BroadcastTablePlayerChange_EnumChangeType {
	if x != nil {
		return x.ChangeType
	}
	return BroadcastTablePlayerChange_Join
}

func (x *BroadcastTablePlayerChange) GetOnChangePlayer() *BjlPlayer {
	if x != nil {
		return x.OnChangePlayer
	}
	return nil
}

func (x *BroadcastTablePlayerChange) GetAllPlayer() []*BjlPlayer {
	if x != nil {
		return x.AllPlayer
	}
	return nil
}

type BjlPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string  `protobuf:"bytes,1,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Gold     float32 `protobuf:"fixed32,2,opt,name=Gold,proto3" json:"Gold,omitempty"`
	UID      int64   `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
}

func (x *BjlPlayer) Reset() {
	*x = BjlPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BjlPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BjlPlayer) ProtoMessage() {}

func (x *BjlPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BjlPlayer.ProtoReflect.Descriptor instead.
func (*BjlPlayer) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{9}
}

func (x *BjlPlayer) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BjlPlayer) GetGold() float32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *BjlPlayer) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

type ReqJoinDesk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeskId string `protobuf:"bytes,1,opt,name=DeskId,proto3" json:"DeskId,omitempty"`
}

func (x *ReqJoinDesk) Reset() {
	*x = ReqJoinDesk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJoinDesk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJoinDesk) ProtoMessage() {}

func (x *ReqJoinDesk) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJoinDesk.ProtoReflect.Descriptor instead.
func (*ReqJoinDesk) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{10}
}

func (x *ReqJoinDesk) GetDeskId() string {
	if x != nil {
		return x.DeskId
	}
	return ""
}

type RespJoinDesk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus string     `protobuf:"bytes,1,opt,name=GameStatus,proto3" json:"GameStatus,omitempty"` //当前房间的状态
	BetInfos   []*BetInfo `protobuf:"bytes,2,rep,name=BetInfos,proto3" json:"BetInfos,omitempty"`     //桌子上下注信息
}

func (x *RespJoinDesk) Reset() {
	*x = RespJoinDesk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinDesk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinDesk) ProtoMessage() {}

func (x *RespJoinDesk) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinDesk.ProtoReflect.Descriptor instead.
func (*RespJoinDesk) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{11}
}

func (x *RespJoinDesk) GetGameStatus() string {
	if x != nil {
		return x.GameStatus
	}
	return ""
}

func (x *RespJoinDesk) GetBetInfos() []*BetInfo {
	if x != nil {
		return x.BetInfos
	}
	return nil
}

type BetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID   int64       `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`                           //下注的人
	Area  EnumBetArea `protobuf:"varint,2,opt,name=Area,proto3,enum=pb_bjl.EnumBetArea" json:"Area,omitempty"` //下注区域
	Count float32     `protobuf:"fixed32,3,opt,name=Count,proto3" json:"Count,omitempty"`                      //区域内下注额
}

func (x *BetInfo) Reset() {
	*x = BetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetInfo) ProtoMessage() {}

func (x *BetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetInfo.ProtoReflect.Descriptor instead.
func (*BetInfo) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{12}
}

func (x *BetInfo) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *BetInfo) GetArea() EnumBetArea {
	if x != nil {
		return x.Area
	}
	return EnumBetArea_AreaNone
}

func (x *BetInfo) GetCount() float32 {
	if x != nil {
		return x.Count
	}
	return 0
}

//状态机变化
type BroadcastStatusReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus EnumGameStatus `protobuf:"varint,1,opt,name=GameStatus,proto3,enum=pb_bjl.EnumGameStatus" json:"GameStatus,omitempty"` //状态变化
	Time       uint32         `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`                                        //当前状态CD（单位秒）
	RoundId    string         `protobuf:"bytes,3,opt,name=RoundId,proto3" json:"RoundId,omitempty"`
	IsShuffle  bool           `protobuf:"varint,4,opt,name=IsShuffle,proto3" json:"IsShuffle,omitempty"` //是否洗牌（表现动画）
}

func (x *BroadcastStatusReady) Reset() {
	*x = BroadcastStatusReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastStatusReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastStatusReady) ProtoMessage() {}

func (x *BroadcastStatusReady) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastStatusReady.ProtoReflect.Descriptor instead.
func (*BroadcastStatusReady) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{13}
}

func (x *BroadcastStatusReady) GetGameStatus() EnumGameStatus {
	if x != nil {
		return x.GameStatus
	}
	return EnumGameStatus_None
}

func (x *BroadcastStatusReady) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BroadcastStatusReady) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *BroadcastStatusReady) GetIsShuffle() bool {
	if x != nil {
		return x.IsShuffle
	}
	return false
}

type BroadcastStatusBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus EnumGameStatus `protobuf:"varint,1,opt,name=GameStatus,proto3,enum=pb_bjl.EnumGameStatus" json:"GameStatus,omitempty"` //状态变化
	Time       uint32         `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`                                        //当前状态CD（单位秒）
}

func (x *BroadcastStatusBet) Reset() {
	*x = BroadcastStatusBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastStatusBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastStatusBet) ProtoMessage() {}

func (x *BroadcastStatusBet) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastStatusBet.ProtoReflect.Descriptor instead.
func (*BroadcastStatusBet) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{14}
}

func (x *BroadcastStatusBet) GetGameStatus() EnumGameStatus {
	if x != nil {
		return x.GameStatus
	}
	return EnumGameStatus_None
}

func (x *BroadcastStatusBet) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type BroadcastStatusSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus EnumGameStatus `protobuf:"varint,1,opt,name=GameStatus,proto3,enum=pb_bjl.EnumGameStatus" json:"GameStatus,omitempty"` //状态变化
	Time       uint32         `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`                                        //当前状态CD（单位秒）
}

func (x *BroadcastStatusSend) Reset() {
	*x = BroadcastStatusSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastStatusSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastStatusSend) ProtoMessage() {}

func (x *BroadcastStatusSend) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastStatusSend.ProtoReflect.Descriptor instead.
func (*BroadcastStatusSend) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{15}
}

func (x *BroadcastStatusSend) GetGameStatus() EnumGameStatus {
	if x != nil {
		return x.GameStatus
	}
	return EnumGameStatus_None
}

func (x *BroadcastStatusSend) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type BroadcastStatusShow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus EnumGameStatus     `protobuf:"varint,1,opt,name=GameStatus,proto3,enum=pb_bjl.EnumGameStatus" json:"GameStatus,omitempty"` //状态变化
	Time       uint32             `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`                                        //当前状态CD（单位秒）
	Xian       []*pb_common.Poker `protobuf:"bytes,3,rep,name=Xian,proto3" json:"Xian,omitempty"`                                         //闲区域的扑克牌id
	Zhuang     []*pb_common.Poker `protobuf:"bytes,4,rep,name=Zhuang,proto3" json:"Zhuang,omitempty"`                                     //庄区域的扑克牌id
}

func (x *BroadcastStatusShow) Reset() {
	*x = BroadcastStatusShow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastStatusShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastStatusShow) ProtoMessage() {}

func (x *BroadcastStatusShow) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastStatusShow.ProtoReflect.Descriptor instead.
func (*BroadcastStatusShow) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{16}
}

func (x *BroadcastStatusShow) GetGameStatus() EnumGameStatus {
	if x != nil {
		return x.GameStatus
	}
	return EnumGameStatus_None
}

func (x *BroadcastStatusShow) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BroadcastStatusShow) GetXian() []*pb_common.Poker {
	if x != nil {
		return x.Xian
	}
	return nil
}

func (x *BroadcastStatusShow) GetZhuang() []*pb_common.Poker {
	if x != nil {
		return x.Zhuang
	}
	return nil
}

//同步玩家下注
type BroadcastPlayerBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *BetInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"` //下注信息
}

func (x *BroadcastPlayerBet) Reset() {
	*x = BroadcastPlayerBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastPlayerBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastPlayerBet) ProtoMessage() {}

func (x *BroadcastPlayerBet) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastPlayerBet.ProtoReflect.Descriptor instead.
func (*BroadcastPlayerBet) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{17}
}

func (x *BroadcastPlayerBet) GetInfo() *BetInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

//玩家自己下注
type ReqBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area  EnumBetArea `protobuf:"varint,1,opt,name=Area,proto3,enum=pb_bjl.EnumBetArea" json:"Area,omitempty"` //下注区域
	Count float32     `protobuf:"fixed32,2,opt,name=Count,proto3" json:"Count,omitempty"`                      //区域内下注总额
}

func (x *ReqBet) Reset() {
	*x = ReqBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBet) ProtoMessage() {}

func (x *ReqBet) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBet.ProtoReflect.Descriptor instead.
func (*ReqBet) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{18}
}

func (x *ReqBet) GetArea() EnumBetArea {
	if x != nil {
		return x.Area
	}
	return EnumBetArea_AreaNone
}

func (x *ReqBet) GetCount() float32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RespBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"` // ok或err
	Gold    float32           `protobuf:"fixed32,2,opt,name=Gold,proto3" json:"Gold,omitempty"`                             //下注后的金币
}

func (x *RespBet) Reset() {
	*x = RespBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBet) ProtoMessage() {}

func (x *RespBet) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespBet.ProtoReflect.Descriptor instead.
func (*RespBet) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{19}
}

func (x *RespBet) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

func (x *RespBet) GetGold() float32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinType     EnumWinType `protobuf:"varint,1,opt,name=WinType,proto3,enum=pb_bjl.EnumWinType" json:"WinType,omitempty"`
	IsXianDui   bool        `protobuf:"varint,2,opt,name=IsXianDui,proto3" json:"IsXianDui,omitempty"`
	IsZhuangDui bool        `protobuf:"varint,3,opt,name=IsZhuangDui,proto3" json:"IsZhuangDui,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{20}
}

func (x *Result) GetWinType() EnumWinType {
	if x != nil {
		return x.WinType
	}
	return EnumWinType_Xian
}

func (x *Result) GetIsXianDui() bool {
	if x != nil {
		return x.IsXianDui
	}
	return false
}

func (x *Result) GetIsZhuangDui() bool {
	if x != nil {
		return x.IsZhuangDui
	}
	return false
}

type BroadcastStatusSettle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus EnumGameStatus                   `protobuf:"varint,1,opt,name=GameStatus,proto3,enum=pb_bjl.EnumGameStatus" json:"GameStatus,omitempty"` //状态变化
	Time       uint32                           `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`                                        //当前状态CD（单位秒）
	Result     *Result                          `protobuf:"bytes,3,opt,name=Result,proto3" json:"Result,omitempty"`                                     //结算结果
	Info       []*BroadcastStatusSettle_WinInfo `protobuf:"bytes,4,rep,name=Info,proto3" json:"Info,omitempty"`
}

func (x *BroadcastStatusSettle) Reset() {
	*x = BroadcastStatusSettle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastStatusSettle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastStatusSettle) ProtoMessage() {}

func (x *BroadcastStatusSettle) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastStatusSettle.ProtoReflect.Descriptor instead.
func (*BroadcastStatusSettle) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{21}
}

func (x *BroadcastStatusSettle) GetGameStatus() EnumGameStatus {
	if x != nil {
		return x.GameStatus
	}
	return EnumGameStatus_None
}

func (x *BroadcastStatusSettle) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BroadcastStatusSettle) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BroadcastStatusSettle) GetInfo() []*BroadcastStatusSettle_WinInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type BroadcastStatusSettle_WinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID        int64   `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`                //下注的人
	GoldChange float32 `protobuf:"fixed32,2,opt,name=GoldChange,proto3" json:"GoldChange,omitempty"` //每个玩家自己的钱的增量
	Gold       float32 `protobuf:"fixed32,3,opt,name=Gold,proto3" json:"Gold,omitempty"`             //每个玩家自己的钱的总量
}

func (x *BroadcastStatusSettle_WinInfo) Reset() {
	*x = BroadcastStatusSettle_WinInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastStatusSettle_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastStatusSettle_WinInfo) ProtoMessage() {}

func (x *BroadcastStatusSettle_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastStatusSettle_WinInfo.ProtoReflect.Descriptor instead.
func (*BroadcastStatusSettle_WinInfo) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{21, 0}
}

func (x *BroadcastStatusSettle_WinInfo) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *BroadcastStatusSettle_WinInfo) GetGoldChange() float32 {
	if x != nil {
		return x.GoldChange
	}
	return 0
}

func (x *BroadcastStatusSettle_WinInfo) GetGold() float32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

var File_bjl_proto protoreflect.FileDescriptor

var file_bjl_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x6a, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f,
	0x62, 0x6a, 0x6c, 0x1a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a,
	0x0c, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6a, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x0c, 0x52,
	0x65, 0x73, 0x70, 0x43, 0x72, 0x65, 0x74, 0x65, 0x42, 0x6a, 0x6c, 0x12, 0x2c, 0x0a, 0x07, 0x45,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70,
	0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x14, 0x52, 0x65, 0x71,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x49, 0x64, 0x12,
	0x28, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a, 0x15, 0x52, 0x65, 0x73,
	0x70, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x35, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x41, 0x6c, 0x6c, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x86, 0x02, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x49,
	0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x29, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x45,
	0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x11, 0x6f, 0x6e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x41, 0x6c,
	0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x2d, 0x0a, 0x0e, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x6e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x10, 0x01,
	0x22, 0x28, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0d, 0x52, 0x65,
	0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x45,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70,
	0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x82, 0x02, 0x0a, 0x1a, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x51, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x70,
	0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x4f,
	0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x42, 0x6a, 0x6c,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0e, 0x4f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x62,
	0x6a, 0x6c, 0x2e, 0x42, 0x6a, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x09, 0x41, 0x6c,
	0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x0e, 0x45, 0x6e, 0x75, 0x6d, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x6f, 0x69,
	0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x10, 0x01, 0x22, 0x4d,
	0x0a, 0x09, 0x42, 0x6a, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44, 0x22, 0x25, 0x0a,
	0x0b, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x44, 0x65, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65,
	0x73, 0x6b, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e,
	0x44, 0x65, 0x73, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e,
	0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x22, 0x5a, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x27,
	0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x42, 0x65, 0x74, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9a, 0x01,
	0x0a, 0x14, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x36, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f,
	0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x49, 0x73, 0x53, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x49, 0x73, 0x53, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x22, 0x60, 0x0a, 0x12, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x65, 0x74,
	0x12, 0x36, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e,
	0x75, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x13,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53,
	0x65, 0x6e, 0x64, 0x12, 0x36, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c,
	0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0xb1, 0x01, 0x0a, 0x13, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x36, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x58, 0x69, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f,
	0x6b, 0x65, 0x72, 0x52, 0x04, 0x58, 0x69, 0x61, 0x6e, 0x12, 0x28, 0x0a, 0x06, 0x5a, 0x68, 0x75,
	0x61, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x5a, 0x68, 0x75,
	0x61, 0x6e, 0x67, 0x22, 0x39, 0x0a, 0x12, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c,
	0x2e, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x47,
	0x0a, 0x06, 0x52, 0x65, 0x71, 0x42, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x42, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x04, 0x41, 0x72, 0x65,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4b, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x65, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x47, 0x6f, 0x6c, 0x64, 0x22, 0x77, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2d,
	0x0a, 0x07, 0x57, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x57, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x57, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x49, 0x73, 0x58, 0x69, 0x61, 0x6e, 0x44, 0x75, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x49, 0x73, 0x58, 0x69, 0x61, 0x6e, 0x44, 0x75, 0x69, 0x12, 0x20, 0x0a, 0x0b, 0x49,
	0x73, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x44, 0x75, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x49, 0x73, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x44, 0x75, 0x69, 0x22, 0x97, 0x02,
	0x0a, 0x15, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x04, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x62, 0x5f, 0x62,
	0x6a, 0x6c, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x57, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x4f, 0x0a, 0x07, 0x57, 0x69, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x55, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x47, 0x6f, 0x6c, 0x64, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x2a, 0x69, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x42,
	0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x65, 0x61, 0x4e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x65, 0x61, 0x58, 0x69, 0x61, 0x6e,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x72, 0x65, 0x61, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x72, 0x65, 0x61, 0x48, 0x65, 0x10, 0x03, 0x12, 0x0f,
	0x0a, 0x0b, 0x41, 0x72, 0x65, 0x61, 0x58, 0x69, 0x61, 0x6e, 0x44, 0x75, 0x69, 0x10, 0x04, 0x12,
	0x11, 0x0a, 0x0d, 0x41, 0x72, 0x65, 0x61, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x44, 0x75, 0x69,
	0x10, 0x05, 0x2a, 0x4e, 0x0a, 0x0e, 0x45, 0x6e, 0x75, 0x6d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x65, 0x74,
	0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04,
	0x53, 0x68, 0x6f, 0x77, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x10, 0x05, 0x2a, 0x2b, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x57, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x58, 0x69, 0x61, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x5a,
	0x68, 0x75, 0x61, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x48, 0x65, 0x10, 0x02, 0x42,
	0x1b, 0x5a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f,
	0x62, 0x6a, 0x6c, 0xaa, 0x02, 0x06, 0x50, 0x62, 0x2e, 0x42, 0x6a, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bjl_proto_rawDescOnce sync.Once
	file_bjl_proto_rawDescData = file_bjl_proto_rawDesc
)

func file_bjl_proto_rawDescGZIP() []byte {
	file_bjl_proto_rawDescOnce.Do(func() {
		file_bjl_proto_rawDescData = protoimpl.X.CompressGZIP(file_bjl_proto_rawDescData)
	})
	return file_bjl_proto_rawDescData
}

var file_bjl_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_bjl_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_bjl_proto_goTypes = []interface{}{
	(EnumBetArea)(0),                               // 0: pb_bjl.EnumBetArea
	(EnumGameStatus)(0),                            // 1: pb_bjl.EnumGameStatus
	(EnumWinType)(0),                               // 2: pb_bjl.EnumWinType
	(PushRoomInfoChange_EnumChangeType)(0),         // 3: pb_bjl.PushRoomInfoChange.EnumChangeType
	(BroadcastTablePlayerChange_EnumChangeType)(0), // 4: pb_bjl.BroadcastTablePlayerChange.EnumChangeType
	(*ReqCreateBjl)(nil),                           // 5: pb_bjl.ReqCreateBjl
	(*RespCreteBjl)(nil),                           // 6: pb_bjl.RespCreteBjl
	(*ReqSubscribeRoomInfo)(nil),                   // 7: pb_bjl.ReqSubscribeRoomInfo
	(*TableInfo)(nil),                              // 8: pb_bjl.TableInfo
	(*RespSubscribeRoomInfo)(nil),                  // 9: pb_bjl.RespSubscribeRoomInfo
	(*PushRoomInfoChange)(nil),                     // 10: pb_bjl.PushRoomInfoChange
	(*ReqJoinTable)(nil),                           // 11: pb_bjl.ReqJoinTable
	(*RespJoinTable)(nil),                          // 12: pb_bjl.RespJoinTable
	(*BroadcastTablePlayerChange)(nil),             // 13: pb_bjl.BroadcastTablePlayerChange
	(*BjlPlayer)(nil),                              // 14: pb_bjl.BjlPlayer
	(*ReqJoinDesk)(nil),                            // 15: pb_bjl.ReqJoinDesk
	(*RespJoinDesk)(nil),                           // 16: pb_bjl.RespJoinDesk
	(*BetInfo)(nil),                                // 17: pb_bjl.BetInfo
	(*BroadcastStatusReady)(nil),                   // 18: pb_bjl.BroadcastStatusReady
	(*BroadcastStatusBet)(nil),                     // 19: pb_bjl.BroadcastStatusBet
	(*BroadcastStatusSend)(nil),                    // 20: pb_bjl.BroadcastStatusSend
	(*BroadcastStatusShow)(nil),                    // 21: pb_bjl.BroadcastStatusShow
	(*BroadcastPlayerBet)(nil),                     // 22: pb_bjl.BroadcastPlayerBet
	(*ReqBet)(nil),                                 // 23: pb_bjl.ReqBet
	(*RespBet)(nil),                                // 24: pb_bjl.RespBet
	(*Result)(nil),                                 // 25: pb_bjl.Result
	(*BroadcastStatusSettle)(nil),                  // 26: pb_bjl.BroadcastStatusSettle
	(*BroadcastStatusSettle_WinInfo)(nil),          // 27: pb_bjl.BroadcastStatusSettle.WinInfo
	(pb_enum.ErrorCode)(0),                         // 28: pb_enum.ErrorCode
	(*pb_common.Poker)(nil),                        // 29: pb_common.Poker
}
var file_bjl_proto_depIdxs = []int32{
	28, // 0: pb_bjl.RespCreteBjl.ErrCode:type_name -> pb_enum.ErrorCode
	28, // 1: pb_bjl.RespSubscribeRoomInfo.ErrCode:type_name -> pb_enum.ErrorCode
	8,  // 2: pb_bjl.RespSubscribeRoomInfo.AllTableInfo:type_name -> pb_bjl.TableInfo
	3,  // 3: pb_bjl.PushRoomInfoChange.ChangeType:type_name -> pb_bjl.PushRoomInfoChange.EnumChangeType
	8,  // 4: pb_bjl.PushRoomInfoChange.onChangeTableInfo:type_name -> pb_bjl.TableInfo
	8,  // 5: pb_bjl.PushRoomInfoChange.AllTableInfo:type_name -> pb_bjl.TableInfo
	28, // 6: pb_bjl.RespJoinTable.ErrCode:type_name -> pb_enum.ErrorCode
	4,  // 7: pb_bjl.BroadcastTablePlayerChange.ChangeType:type_name -> pb_bjl.BroadcastTablePlayerChange.EnumChangeType
	14, // 8: pb_bjl.BroadcastTablePlayerChange.OnChangePlayer:type_name -> pb_bjl.BjlPlayer
	14, // 9: pb_bjl.BroadcastTablePlayerChange.AllPlayer:type_name -> pb_bjl.BjlPlayer
	17, // 10: pb_bjl.RespJoinDesk.BetInfos:type_name -> pb_bjl.BetInfo
	0,  // 11: pb_bjl.BetInfo.Area:type_name -> pb_bjl.EnumBetArea
	1,  // 12: pb_bjl.BroadcastStatusReady.GameStatus:type_name -> pb_bjl.EnumGameStatus
	1,  // 13: pb_bjl.BroadcastStatusBet.GameStatus:type_name -> pb_bjl.EnumGameStatus
	1,  // 14: pb_bjl.BroadcastStatusSend.GameStatus:type_name -> pb_bjl.EnumGameStatus
	1,  // 15: pb_bjl.BroadcastStatusShow.GameStatus:type_name -> pb_bjl.EnumGameStatus
	29, // 16: pb_bjl.BroadcastStatusShow.Xian:type_name -> pb_common.Poker
	29, // 17: pb_bjl.BroadcastStatusShow.Zhuang:type_name -> pb_common.Poker
	17, // 18: pb_bjl.BroadcastPlayerBet.Info:type_name -> pb_bjl.BetInfo
	0,  // 19: pb_bjl.ReqBet.Area:type_name -> pb_bjl.EnumBetArea
	28, // 20: pb_bjl.RespBet.ErrCode:type_name -> pb_enum.ErrorCode
	2,  // 21: pb_bjl.Result.WinType:type_name -> pb_bjl.EnumWinType
	1,  // 22: pb_bjl.BroadcastStatusSettle.GameStatus:type_name -> pb_bjl.EnumGameStatus
	25, // 23: pb_bjl.BroadcastStatusSettle.Result:type_name -> pb_bjl.Result
	27, // 24: pb_bjl.BroadcastStatusSettle.Info:type_name -> pb_bjl.BroadcastStatusSettle.WinInfo
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_bjl_proto_init() }
func file_bjl_proto_init() {
	if File_bjl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bjl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCreateBjl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespCreteBjl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSubscribeRoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespSubscribeRoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushRoomInfoChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqJoinTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastTablePlayerChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BjlPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqJoinDesk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinDesk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastStatusReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastStatusBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastStatusSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastStatusShow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastPlayerBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastStatusSettle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastStatusSettle_WinInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bjl_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bjl_proto_goTypes,
		DependencyIndexes: file_bjl_proto_depIdxs,
		EnumInfos:         file_bjl_proto_enumTypes,
		MessageInfos:      file_bjl_proto_msgTypes,
	}.Build()
	File_bjl_proto = out.File
	file_bjl_proto_rawDesc = nil
	file_bjl_proto_goTypes = nil
	file_bjl_proto_depIdxs = nil
}
