// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: tetris.proto

package pb_tetris

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_enum "server/pb/pb_enum"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRoomInfoChange_EnumChangeType int32

const (
	PushRoomInfoChange_OnCreate  PushRoomInfoChange_EnumChangeType = 0 //创建
	PushRoomInfoChange_OnDestroy PushRoomInfoChange_EnumChangeType = 1 //销毁
)

// Enum value maps for PushRoomInfoChange_EnumChangeType.
var (
	PushRoomInfoChange_EnumChangeType_name = map[int32]string{
		0: "OnCreate",
		1: "OnDestroy",
	}
	PushRoomInfoChange_EnumChangeType_value = map[string]int32{
		"OnCreate":  0,
		"OnDestroy": 1,
	}
)

func (x PushRoomInfoChange_EnumChangeType) Enum() *PushRoomInfoChange_EnumChangeType {
	p := new(PushRoomInfoChange_EnumChangeType)
	*p = x
	return p
}

func (x PushRoomInfoChange_EnumChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushRoomInfoChange_EnumChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_tetris_proto_enumTypes[0].Descriptor()
}

func (PushRoomInfoChange_EnumChangeType) Type() protoreflect.EnumType {
	return &file_tetris_proto_enumTypes[0]
}

func (x PushRoomInfoChange_EnumChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushRoomInfoChange_EnumChangeType.Descriptor instead.
func (PushRoomInfoChange_EnumChangeType) EnumDescriptor() ([]byte, []int) {
	return file_tetris_proto_rawDescGZIP(), []int{5, 0}
}

type ReqCreateTetris struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"` //游戏桌子名称
}

func (x *ReqCreateTetris) Reset() {
	*x = ReqCreateTetris{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tetris_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCreateTetris) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateTetris) ProtoMessage() {}

func (x *ReqCreateTetris) ProtoReflect() protoreflect.Message {
	mi := &file_tetris_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateTetris.ProtoReflect.Descriptor instead.
func (*ReqCreateTetris) Descriptor() ([]byte, []int) {
	return file_tetris_proto_rawDescGZIP(), []int{0}
}

func (x *ReqCreateTetris) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type RespCreteTetris struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"`
	ID      string            `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"` //服务器创建成功后返回的桌子的ID
}

func (x *RespCreteTetris) Reset() {
	*x = RespCreteTetris{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tetris_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespCreteTetris) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespCreteTetris) ProtoMessage() {}

func (x *RespCreteTetris) ProtoReflect() protoreflect.Message {
	mi := &file_tetris_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespCreteTetris.ProtoReflect.Descriptor instead.
func (*RespCreteTetris) Descriptor() ([]byte, []int) {
	return file_tetris_proto_rawDescGZIP(), []int{1}
}

func (x *RespCreteTetris) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

func (x *RespCreteTetris) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

//是否订阅房间消息
type ReqSubscribeRoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSubscribe bool `protobuf:"varint,1,opt,name=IsSubscribe,proto3" json:"IsSubscribe,omitempty"` // true,开始订阅，false,取消订阅
}

func (x *ReqSubscribeRoomInfo) Reset() {
	*x = ReqSubscribeRoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tetris_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSubscribeRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSubscribeRoomInfo) ProtoMessage() {}

func (x *ReqSubscribeRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tetris_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSubscribeRoomInfo.ProtoReflect.Descriptor instead.
func (*ReqSubscribeRoomInfo) Descriptor() ([]byte, []int) {
	return file_tetris_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSubscribeRoomInfo) GetIsSubscribe() bool {
	if x != nil {
		return x.IsSubscribe
	}
	return false
}

//服务器向客户端同步房间信息
type TableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId         string `protobuf:"bytes,1,opt,name=TableId,proto3" json:"TableId,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatorUId      string `protobuf:"bytes,3,opt,name=CreatorUId,proto3" json:"CreatorUId,omitempty"`
	CreatorNickName string `protobuf:"bytes,4,opt,name=CreatorNickName,proto3" json:"CreatorNickName,omitempty"`
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tetris_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tetris_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_tetris_proto_rawDescGZIP(), []int{3}
}

func (x *TableInfo) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *TableInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableInfo) GetCreatorUId() string {
	if x != nil {
		return x.CreatorUId
	}
	return ""
}

func (x *TableInfo) GetCreatorNickName() string {
	if x != nil {
		return x.CreatorNickName
	}
	return ""
}

type RespSubscribeRoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode      pb_enum.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=pb_enum.ErrorCode" json:"ErrCode,omitempty"`
	AllTableInfo []*TableInfo      `protobuf:"bytes,2,rep,name=AllTableInfo,proto3" json:"AllTableInfo,omitempty"`
}

func (x *RespSubscribeRoomInfo) Reset() {
	*x = RespSubscribeRoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tetris_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespSubscribeRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSubscribeRoomInfo) ProtoMessage() {}

func (x *RespSubscribeRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tetris_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSubscribeRoomInfo.ProtoReflect.Descriptor instead.
func (*RespSubscribeRoomInfo) Descriptor() ([]byte, []int) {
	return file_tetris_proto_rawDescGZIP(), []int{4}
}

func (x *RespSubscribeRoomInfo) GetErrCode() pb_enum.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_enum.ErrorCode_Default
}

func (x *RespSubscribeRoomInfo) GetAllTableInfo() []*TableInfo {
	if x != nil {
		return x.AllTableInfo
	}
	return nil
}

type PushRoomInfoChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangeType        PushRoomInfoChange_EnumChangeType `protobuf:"varint,1,opt,name=ChangeType,proto3,enum=pb_tetris.PushRoomInfoChange_EnumChangeType" json:"ChangeType,omitempty"`
	OnChangeTableInfo *TableInfo                        `protobuf:"bytes,2,opt,name=onChangeTableInfo,proto3" json:"onChangeTableInfo,omitempty"` //变化量
	AllTableInfo      []*TableInfo                      `protobuf:"bytes,3,rep,name=AllTableInfo,proto3" json:"AllTableInfo,omitempty"`           //总量
}

func (x *PushRoomInfoChange) Reset() {
	*x = PushRoomInfoChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tetris_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushRoomInfoChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomInfoChange) ProtoMessage() {}

func (x *PushRoomInfoChange) ProtoReflect() protoreflect.Message {
	mi := &file_tetris_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomInfoChange.ProtoReflect.Descriptor instead.
func (*PushRoomInfoChange) Descriptor() ([]byte, []int) {
	return file_tetris_proto_rawDescGZIP(), []int{5}
}

func (x *PushRoomInfoChange) GetChangeType() PushRoomInfoChange_EnumChangeType {
	if x != nil {
		return x.ChangeType
	}
	return PushRoomInfoChange_OnCreate
}

func (x *PushRoomInfoChange) GetOnChangeTableInfo() *TableInfo {
	if x != nil {
		return x.OnChangeTableInfo
	}
	return nil
}

func (x *PushRoomInfoChange) GetAllTableInfo() []*TableInfo {
	if x != nil {
		return x.AllTableInfo
	}
	return nil
}

var File_tetris_proto protoreflect.FileDescriptor

var file_tetris_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x65, 0x74, 0x72, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x70, 0x62, 0x5f, 0x74, 0x65, 0x74, 0x72, 0x69, 0x73, 0x1a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x65, 0x74, 0x72, 0x69, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x43, 0x72,
	0x65, 0x74, 0x65, 0x54, 0x65, 0x74, 0x72, 0x69, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x45, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f,
	0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07,
	0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x20, 0x0a, 0x0b, 0x49, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x22, 0x83, 0x01, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x4e,
	0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7f, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2c, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x38,
	0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x74, 0x72, 0x69, 0x73,
	0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x41, 0x6c, 0x6c, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x8f, 0x02, 0x0a, 0x12, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x4c, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x74, 0x72, 0x69, 0x73, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x42, 0x0a,
	0x11, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x5f, 0x74, 0x65,
	0x74, 0x72, 0x69, 0x73, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11,
	0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x38, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x74,
	0x72, 0x69, 0x73, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x41,
	0x6c, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2d, 0x0a, 0x0e, 0x45,
	0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a,
	0x08, 0x4f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f,
	0x6e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x10, 0x01, 0x42, 0x21, 0x5a, 0x13, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x74, 0x72, 0x69,
	0x73, 0xaa, 0x02, 0x09, 0x50, 0x62, 0x2e, 0x54, 0x65, 0x74, 0x72, 0x69, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tetris_proto_rawDescOnce sync.Once
	file_tetris_proto_rawDescData = file_tetris_proto_rawDesc
)

func file_tetris_proto_rawDescGZIP() []byte {
	file_tetris_proto_rawDescOnce.Do(func() {
		file_tetris_proto_rawDescData = protoimpl.X.CompressGZIP(file_tetris_proto_rawDescData)
	})
	return file_tetris_proto_rawDescData
}

var file_tetris_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tetris_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tetris_proto_goTypes = []interface{}{
	(PushRoomInfoChange_EnumChangeType)(0), // 0: pb_tetris.PushRoomInfoChange.EnumChangeType
	(*ReqCreateTetris)(nil),                // 1: pb_tetris.ReqCreateTetris
	(*RespCreteTetris)(nil),                // 2: pb_tetris.RespCreteTetris
	(*ReqSubscribeRoomInfo)(nil),           // 3: pb_tetris.ReqSubscribeRoomInfo
	(*TableInfo)(nil),                      // 4: pb_tetris.TableInfo
	(*RespSubscribeRoomInfo)(nil),          // 5: pb_tetris.RespSubscribeRoomInfo
	(*PushRoomInfoChange)(nil),             // 6: pb_tetris.PushRoomInfoChange
	(pb_enum.ErrorCode)(0),                 // 7: pb_enum.ErrorCode
}
var file_tetris_proto_depIdxs = []int32{
	7, // 0: pb_tetris.RespCreteTetris.ErrCode:type_name -> pb_enum.ErrorCode
	7, // 1: pb_tetris.RespSubscribeRoomInfo.ErrCode:type_name -> pb_enum.ErrorCode
	4, // 2: pb_tetris.RespSubscribeRoomInfo.AllTableInfo:type_name -> pb_tetris.TableInfo
	0, // 3: pb_tetris.PushRoomInfoChange.ChangeType:type_name -> pb_tetris.PushRoomInfoChange.EnumChangeType
	4, // 4: pb_tetris.PushRoomInfoChange.onChangeTableInfo:type_name -> pb_tetris.TableInfo
	4, // 5: pb_tetris.PushRoomInfoChange.AllTableInfo:type_name -> pb_tetris.TableInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tetris_proto_init() }
func file_tetris_proto_init() {
	if File_tetris_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tetris_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCreateTetris); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tetris_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespCreteTetris); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tetris_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSubscribeRoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tetris_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tetris_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespSubscribeRoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tetris_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushRoomInfoChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tetris_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tetris_proto_goTypes,
		DependencyIndexes: file_tetris_proto_depIdxs,
		EnumInfos:         file_tetris_proto_enumTypes,
		MessageInfos:      file_tetris_proto_msgTypes,
	}.Build()
	File_tetris_proto = out.File
	file_tetris_proto_rawDesc = nil
	file_tetris_proto_goTypes = nil
	file_tetris_proto_depIdxs = nil
}
